//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TID { get; set; }
        public int MID { get; set; }
        public int UID { get; set; }
        public int MTLID { get; set; }
        public int WID { get; set; }
        public int NumberOfDone { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Management Management { get; set; }
        public virtual User User { get; set; }
        public virtual YearWeek YearWeek { get; set; }
    }
}
