//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBL2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KHBEntities : DbContext
    {
        public KHBEntities()
            : base("name=KHBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Management> Managements { get; set; }
        public virtual DbSet<ManagementsTasksLookup> ManagementsTasksLookups { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<YearWeek> YearWeeks { get; set; }
        public virtual DbSet<ManagementField> ManagementFields { get; set; }
        public virtual DbSet<Managements1> Managements1 { get; set; }
        public virtual DbSet<User_Has_Fields> User_Has_Fields { get; set; }
        public virtual DbSet<Users1> Users1 { get; set; }
    }
}
