//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users1()
        {
            this.User_Has_Fields = new HashSet<User_Has_Fields>();
        }
    
        public int ID { get; set; }
        public int MID { get; set; }
        public string UserEmail { get; set; }
        public string UserFullName { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Managements1 Managements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Has_Fields> User_Has_Fields { get; set; }
    }
}
