//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Has_Fields
    {
        public int ID { get; set; }
        public int UID { get; set; }
        public int MFID { get; set; }
        public int WeekNumber { get; set; }
    
        public virtual Users1 Users1 { get; set; }
    }
}
